name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compression_test:
    name: Test Compression
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pycryptodome
          pip install -e .

      - name: Run compression tests
        run: pytest tests/test_compression.py -v

  filelock_test:
    name: Test FileLock
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pycryptodome
          pip install -e .  # Install the package in development mode

      - name: Run filelock tests
        run: |
          coverage run -m pytest tests/test_filelock.py -v
          coverage report --include="src/filelock.py"

  integration_test:
    name: Test Integration
    needs: [compression_test, filelock_test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pycryptodome
          pip install -e .

      - name: Run integration tests
        run: pytest tests/test_integration.py -v
